-- MySQL Script generated by MySQL Workbench
-- Mon Oct  9 22:25:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`logins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`logins` ;

CREATE TABLE IF NOT EXISTS `mydb`.`logins` (
  `loginID` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `permission` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`loginID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `adminID` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `dateOfBirth` DATE NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `phoneNumber` INT(11) NULL DEFAULT NULL,
  `mobileNumber` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `faceBook` VARCHAR(45) NULL DEFAULT NULL,
  `loginID` INT NOT NULL,
  PRIMARY KEY (`adminID`),
  INDEX `fk_admin_logins_idx` (`loginID` ASC),
  CONSTRAINT `fk_admin_logins`
    FOREIGN KEY (`loginID`)
    REFERENCES `mydb`.`logins` (`loginID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`students` ;

CREATE TABLE IF NOT EXISTS `mydb`.`students` (
  `studentID` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `dateOfBirth` DATE NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `phoneNumber` INT(11) NULL DEFAULT NULL,
  `mobileNumber` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `faceBook` VARCHAR(45) NULL DEFAULT NULL,
  `grade` VARCHAR(15) NULL DEFAULT NULL,
  `loginID` INT(11) NOT NULL,
  PRIMARY KEY (`studentID`),
  INDEX `fk_students_logins1_idx` (`loginID` ASC),
  CONSTRAINT `fk_students_logins1`
    FOREIGN KEY (`loginID`)
    REFERENCES `mydb`.`logins` (`loginID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tourists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tourists` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tourists` (
  `touristID` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `dateOfBirth` DATE NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `phoneNumber` INT(11) NULL DEFAULT NULL,
  `mobileNumber` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `faceBook` VARCHAR(45) NULL DEFAULT NULL,
  `loginID` INT NOT NULL,
  PRIMARY KEY (`touristID`),
  INDEX `fk_students_logins1_idx` (`loginID` ASC),
  CONSTRAINT `fk_students_logins10`
    FOREIGN KEY (`loginID`)
    REFERENCES `mydb`.`logins` (`loginID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`businessmen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`businessmen` ;

CREATE TABLE IF NOT EXISTS `mydb`.`businessmen` (
  `businessmenID` INT NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `dateOfBirth` DATE NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `phoneNumber` INT(11) NULL DEFAULT NULL,
  `mobileNumber` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `faceBook` VARCHAR(45) NULL DEFAULT NULL,
  `loginID` INT NOT NULL,
  PRIMARY KEY (`businessmenID`),
  INDEX `fk_students_logins1_idx` (`loginID` ASC),
  CONSTRAINT `fk_students_logins11`
    FOREIGN KEY (`loginID`)
    REFERENCES `mydb`.`logins` (`loginID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cities` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cities` (
  `cityID` INT NOT NULL,
  `cityName` VARCHAR(45) NOT NULL,
  `buildingID` INT NOT NULL,
  PRIMARY KEY (`cityID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`languages` ;

CREATE TABLE IF NOT EXISTS `mydb`.`languages` (
  `languageID` INT NOT NULL,
  `languageName` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`languageID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`places`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`places` ;

CREATE TABLE IF NOT EXISTS `mydb`.`places` (
  `placeID` INT NOT NULL,
  `placeName` VARCHAR(45) NOT NULL,
  `cityID` INT NOT NULL,
  PRIMARY KEY (`placeID`),
  INDEX `fk_places_cities1_idx` (`cityID` ASC),
  CONSTRAINT `fk_places_cities1`
    FOREIGN KEY (`cityID`)
    REFERENCES `mydb`.`cities` (`cityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`buildings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`buildings` ;

CREATE TABLE IF NOT EXISTS `mydb`.`buildings` (
  `buildingID` INT NOT NULL,
  `buildingName` VARCHAR(45) NOT NULL,
  `cityID` INT NOT NULL,
  PRIMARY KEY (`buildingID`),
  INDEX `fk_buildings_cities1_idx` (`cityID` ASC),
  CONSTRAINT `fk_buildings_cities1`
    FOREIGN KEY (`cityID`)
    REFERENCES `mydb`.`cities` (`cityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`colleges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`colleges` ;

CREATE TABLE IF NOT EXISTS `mydb`.`colleges` (
  `collegeID` INT NOT NULL,
  `collegeName` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `departments` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phoneNumber` INT(11) NOT NULL,
  `buildingID` INT NOT NULL,
  PRIMARY KEY (`collegeID`),
  INDEX `fk_colleges_buildings1_idx` (`buildingID` ASC),
  CONSTRAINT `fk_colleges_buildings1`
    FOREIGN KEY (`buildingID`)
    REFERENCES `mydb`.`buildings` (`buildingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`libraries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`libraries` ;

CREATE TABLE IF NOT EXISTS `mydb`.`libraries` (
  `libraryID` INT NOT NULL,
  `collegeName` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phoneNumber` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `buildingID` INT NOT NULL,
  PRIMARY KEY (`libraryID`),
  INDEX `fk_libraries_buildings1_idx` (`buildingID` ASC),
  CONSTRAINT `fk_libraries_buildings1`
    FOREIGN KEY (`buildingID`)
    REFERENCES `mydb`.`buildings` (`buildingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`industries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`industries` ;

CREATE TABLE IF NOT EXISTS `mydb`.`industries` (
  `industryID` INT NOT NULL,
  `industryName` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `departments` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phoneNumber` INT(11) NOT NULL,
  `buildingID` INT NOT NULL,
  PRIMARY KEY (`industryID`),
  INDEX `fk_industries_buildings1_idx` (`buildingID` ASC),
  CONSTRAINT `fk_industries_buildings1`
    FOREIGN KEY (`buildingID`)
    REFERENCES `mydb`.`buildings` (`buildingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hotels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hotels` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hotels` (
  `hotelID` INT NOT NULL,
  `hotelName` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `departments` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phoneNumber` INT(11) NOT NULL,
  `buildingID` INT NOT NULL,
  PRIMARY KEY (`hotelID`),
  INDEX `fk_hotels_buildings1_idx` (`buildingID` ASC),
  CONSTRAINT `fk_hotels_buildings1`
    FOREIGN KEY (`buildingID`)
    REFERENCES `mydb`.`buildings` (`buildingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`parks` ;

CREATE TABLE IF NOT EXISTS `mydb`.`parks` (
  `parkID` INT NOT NULL,
  `parkName` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phoneNumber` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `placeID` INT NOT NULL,
  PRIMARY KEY (`parkID`),
  INDEX `fk_parks_places1_idx` (`placeID` ASC),
  CONSTRAINT `fk_parks_places1`
    FOREIGN KEY (`placeID`)
    REFERENCES `mydb`.`places` (`placeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zoos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`zoos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`zoos` (
  `zooID` INT NOT NULL,
  `zooName` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phoneNumber` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `placeID` INT NOT NULL,
  PRIMARY KEY (`zooID`),
  INDEX `fk_zoos_places1_idx` (`placeID` ASC),
  CONSTRAINT `fk_zoos_places1`
    FOREIGN KEY (`placeID`)
    REFERENCES `mydb`.`places` (`placeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`restaurants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`restaurants` ;

CREATE TABLE IF NOT EXISTS `mydb`.`restaurants` (
  `restaurantID` INT NOT NULL,
  `restaurantName` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phoneNumber` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `placeID` INT NOT NULL,
  PRIMARY KEY (`restaurantID`),
  INDEX `fk_restaurants_places1_idx` (`placeID` ASC),
  CONSTRAINT `fk_restaurants_places1`
    FOREIGN KEY (`placeID`)
    REFERENCES `mydb`.`places` (`placeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`malls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`malls` ;

CREATE TABLE IF NOT EXISTS `mydb`.`malls` (
  `mallID` INT NOT NULL,
  `mallName` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phoneNumber` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `placeID` INT NOT NULL,
  PRIMARY KEY (`mallID`),
  INDEX `fk_malls_places1_idx` (`placeID` ASC),
  CONSTRAINT `fk_malls_places1`
    FOREIGN KEY (`placeID`)
    REFERENCES `mydb`.`places` (`placeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`calender` ;

CREATE TABLE IF NOT EXISTS `mydb`.`calender` (
  `calenderID` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `startDate` VARCHAR(48) NOT NULL,
  `endDate` VARCHAR(48) NOT NULL,
  PRIMARY KEY (`calenderID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
