CREATE DATABASE smartcity_dbase;
USE smartcity_dbase;

CREATE TABLE user (
userId INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
username VARCHAR(16) NOT NULL,
first_name VARCHAR(45) NULL,
last_name VARCHAR(45) NULL, 
email VARCHAR(45) NOT NULL, 
is_superuser VARCHAR(45) NULL,
password VARCHAR(32) NOT NULL,
userType VARCHAR(20) NOT NULL
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE city (
cityId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
state VARCHAR(45) NOT NULL
)ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE college (
collegeId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(45) NOT NULL,
address VARCHAR(45) NOT NULL, 
departments VARCHAR(45) NOT NULL, 
email VARCHAR(45) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_dbaseb.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE hotel (
hotelId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(45) NOT NULL,
address VARCHAR(45) NOT NULL, 
phone INT(20) NOT NULL, 
email VARCHAR(45) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_dbase.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE industry (
industriesId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(45) NOT NULL,
address VARCHAR(45) NOT NULL, 
industryType VARCHAR(500) NOT NULL, 
email VARCHAR(45) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_dbase.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE library (
libraryId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(45) NOT NULL,
address VARCHAR(45) NOT NULL, 
phone INT(20) NOT NULL, 
email VARCHAR(45) NOT NULL,
FOREIGN KEY(cityId) REFERENCES ssmartcity_dbase.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE mall (
mallId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(45) NOT NULL,
address VARCHAR(45) NOT NULL, 
phone INT(20) NOT NULL, 
email VARCHAR(45) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_dbase.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE museum (
museumId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(45) NOT NULL,
address VARCHAR(45) NOT NULL, 
phone INT(20) NOT NULL, 
email VARCHAR(45) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_dbase.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE park (
parkId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(45) NOT NULL,
address VARCHAR(45) NOT NULL, 
phone INT(20) NOT NULL, 
email VARCHAR(45) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_dbase.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE restaurant (
restaurantId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(45) NOT NULL,
address VARCHAR(45) NOT NULL, 
phone INT(20) NOT NULL, 
email VARCHAR(45) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_dbase.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE zoo (
zooId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
cityId INT NOT NULL,
name VARCHAR(45) NOT NULL,
address VARCHAR(45) NOT NULL, 
phone INT(20) NOT NULL, 
email VARCHAR(45) NOT NULL,
FOREIGN KEY(cityId) REFERENCES smartcity_dbase.city(cityId) ON DELETE CASCADE
)ENGINE=MyISAM DEFAULT CHARSET=utf8;