# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Business', 'Business'), ('Student', 'Student'), ('Tourist', 'Tourist'), ('ADMIN', 'ADMIN')], default='Business', max_length=8),
        ),
    ]
